apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:diskmanti/kinder.git
    path: components/argocd-ingress
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd