apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/diskmanti/kinder.git
    path: componenets/nginx-ingress
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd