apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:diskmanti/kinder.git
    path: components/nginx-ingress
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd